apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ofekbarel/test
    targetRevision: HEAD
    path: ./coffeHelm # Path to the helm chart.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true