version: '3.3'
services:
  web:
    image: ofekbarel11/coffeproject:latest
    ports:
      - "5000:5000"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - HOST=postgres


    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    #volumes:
      #- mongodb_data:/data/db