---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: ofekbarel/finalproject
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST #postgres service
              value: postgres
            - name: DB_NAME  #database name
              value: test
            - name: DB_USER  #database username
              value: postgres
            - name: db_root_password #database password from secrets.yml
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
           
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: LoadBalancer